apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:    
  groups:
    - name: main-rules
      rules:
        - alert: HighCpuOrMemoryUsage
          expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 50
                or
                ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100) > 50
          for: 5m
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            summary: "High CPU or Memory Usage Detected"
            description: "High CPU or memory usage detected on instance = {{ $labels.instance }} value = {{$value}}"